CREATE TABLE task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID                                    NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    due_at      TIMESTAMP                               NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMPTZ                             NOT NULL,
    updated_at  TIMESTAMPTZ                             NOT NULL,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE task
    ADD CONSTRAINT uc_task_uuid UNIQUE (uuid);